### ISSUE TITLE
Generate run errors for erb controlled database.yml files

### ISSUE THREAD

**Issue by albus522** [fly-apps/dockerfile-rails#119]
It is relatively easy to have a database.yml file that is invalid yaml before being processed through the erb preprocessor. When this is the case the generate command fails with a `Psych::SyntaxError`.

As a side note, the command probably shouldn't assume it knows best about what the database.yml should be just because a fly.toml file exists.

**Comment by rubys** [comment]
I found one case where database.yml was being parsed as YAML without catching errors, so I fixed that one.  Let me know if there is more.

I really, really, really don't like updating database.yml, but I don't know any other way to solve the problem of Rails 8 defining multiple production databases, where only one is controllable via `DATABASE_URL`.  The experience is lousy: for sqlite3 you get your main database on a volume, but the rest on ephemeral storage.  For postgresql the experience is worse: opening anything other than your primary database results in a failure to find a unix socket as the assumption is that the database server is running on your machine.  If you (or anybody) has any ideas on how to address this without updating database.yml, I'm all ears.
