### ISSUE TITLE
[Suggestion] Prominently warn or error if on arm with no platform specified

### ISSUE THREAD

**Issue by albus522** [fly-apps/dockerfile-rails#39]
We just encountered a deploy issue because we were generating the docker file on an M1 Mac and deploying to x86 without explicitly setting the platform.

Given the intention of this effort is to operate on the principle of least surprise, that most deploy environments are still x86, and M(1|2) Macs are going to be more common, it would be helpful to provide a notice that you may be generating unintentional results without specifying the `--platform` option.

Erroring and asking to declare the `--platform` option might be the cleanest option, but a bit heavy handed. A very obvious warning might be better. The warning/error could be isolated to if `Gem::Platform.local.cpu` is used as a fallback.

**Comment by danielmorrison** [comment]
This is a direct follow up to #27. We got `--jemalloc` working nicely after the fix.

However, deploying to Fly we were still getting errors in our logs: 

> ERROR: ld.so: object '/usr/lib/aarch64-linux-gnu/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

We realized we need to also specify the `--platform linux/amd64` which then sets `LD_PRELOAD` to the expected path properly: 
`LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libjemalloc.so.2"`

**Comment by rubys** [comment]
I'm actually leaning towards erroring.

You saw this in the logs and were able to work backwards and figure it out.  Many won't notice.

It is easy for me to update the fly docs to suggest setting both at the same time, so for most users it will be a matter of copying/pasting a slightly longer string.

To not break users who are currently deployed, I think --platform should default if --jemalloc had **previously** been set

**Comment by rubys** [comment]
This is no longer relevant given the following change: https://github.com/fly-apps/dockerfile-rails/commit/85822c2cccc467637ff2e398ff79926ae033a57f
