### ISSUE TITLE
Add curl

### ISSUE THREAD

**Issue by miharekar** [fly-apps/dockerfile-rails#42]
I understand this isn't meant for mrsk, but it'll be used by many people for that. And mrsk now requires `curl` to be installed.

https://github.com/mrsked/mrsk/issues/276

Maybe add it by default (it's a small package) or via an option?

**Comment by louim** [comment]
Hey! You can already add `curl` (and any other package you want) via the add package command: https://github.com/fly-apps/dockerfile-rails#add-a-packageenvironment-variablebuild-argument

**Comment by rubys** [comment]
> I understand this isn't meant for mrsk, but it'll be used by many people for that.

I want people to use it for mrsk and elsewhere!  I also want this package to track the Dockerfile produced by Rails 7.1.
