### ISSUE TITLE
1.5.2 Dockerfile breaks on ECS

### ISSUE THREAD

**Issue by primdahl** [fly-apps/dockerfile-rails#48]
I upgraded a project from 1.5.1 to 1.5.2 and generated a new Dockerfile. Subsequently, nginx refuses to start:

```
July 29, 2023 at 09:01 (UTC+2:00) 07:01:17 rails.1 | terminated by SIGTERM  staging-web
July 29, 2023 at 09:01 (UTC+2:00) 07:01:17 nginx.1 | exited with code 1 staging-web
July 29, 2023 at 09:01 (UTC+2:00) 07:01:17 system | sending SIGTERM to all processes  staging-web
July 29, 2023 at 09:01 (UTC+2:00) 07:01:16 nginx.1 | 2023/07/29 07:01:16 [emerg] 20#20: open() "/usr/share/nginx/stdout" failed (13: Permission denied) staging-web
July 29, 2023 at 09:01 (UTC+2:00) 07:01:16 nginx.1 | 2023/07/29 07:01:16 [warn] 20#20: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1  staging-web
July 29, 2023 at 09:01 (UTC+2:00) 07:01:16 nginx.1 | started with pid 14  staging-web
July 29, 2023 at 09:01 (UTC+2:00) 07:01:16 rails.1 | started with pid 15
```

This is on AWS ECS. For good measure, the Dockerfile diff:

```diff
diff --git a/Dockerfile b/Dockerfile
index c7220c5..06a329e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -51,14 +51,14 @@ RUN apt-get update -qq && \
 # configure nginx
 RUN gem install foreman && \
     sed -i 's|pid /run|pid /rails/tmp/pids|' /etc/nginx/nginx.conf && \
-    sed -i 's/access_log\s.*;/access_log \/dev\/stdout;/' /etc/nginx/nginx.conf && \
-    sed -i 's/error_log\s.*;/error_log \/dev\/stderr info;/' /etc/nginx/nginx.conf
+    sed -i 's/access_log\s.*;/access_log stdout;/' /etc/nginx/nginx.conf && \
+    sed -i 's/error_log\s.*;/error_log stderr info;/' /etc/nginx/nginx.conf

 COPY <<-"EOF" /etc/nginx/sites-available/default
 server {
   listen 3000 default_server;
   listen [::]:3000 default_server;
-  access_log /dev/stdout;
+  access_log stdout;

   root /rails/public;

@@ -92,7 +92,7 @@ RUN useradd rails --create-home --shell /bin/bash && \
 USER rails:rails

 # Deployment options
-ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libjemalloc.so.2" \
+ENV LD_PRELOAD="libjemalloc.so.2" \
     MALLOC_CONF="dirty_decay_ms:1000,narenas:2,background_thread:true" \
     PORT="3001" \
     RAILS_LOG_TO_STDOUT="1"
```

**Comment by rubys** [comment]
Thanks for the clear diff!

Do you have a `USER` line in your Dockerfile?

**Comment by primdahl** [comment]
It's the vanilla Dockerfile from `dockerfile-rails` generated by ` bin/rails generate dockerfile --postgresql --nginx --jemalloc`, so `USER rails:rails` is there.

I'm also seeing this locally, so not ECS related I just hadn't checked elsewhere:

```
20:05:43 nginx.1 | 2023/07/31 20:05:43 [emerg] 29#29: open() "/usr/share/nginx/stdout" failed (13: Permission denied)
20:05:44 nginx.1 | exited with code 1
```

If I `chown rails:rails /usr/share/nginx` things work. I'm not sure if that's the correct solution since I came across a lot of posts on related issues, like this one:

https://alexanderallen.medium.com/forwarding-nginx-logs-to-docker-3bb6283a207

I tried `RUN adduser rails tty` but couldn't make it work.

**Comment by primdahl** [comment]
The `chown rails:rails /usr/share/nginx` was a red herring, it just makes nginx log to a `/usr/share/nginx/stdout` because `/usr/share/nginx` is the default path, so `access_log stdout` apparently considers the `stdout` to be any old path/file?

**Comment by rubys** [comment]
I no longer remember why I removed `/dev/` in https://github.com/fly-apps/dockerfile-rails/commit/6cd84e2bb757df49014774b2f2a134068bb47708, but the above commit will restore it for non-root users (my app is using passenger).  Please reopen if this doesn't address your problem.  If you confirm that it fixes your problem, I'll make a release.
