### ISSUE TITLE
Don't default to sqlite3, or provide option to disable?

### ISSUE THREAD

**Issue by ttilberg** [fly-apps/dockerfile-rails#61]
I'm using SQL Server in my app. When I build a Dockerfile without specifying a database, it assumes I wish to use Sqlite3.

My Dockerfile is generated with the following additional lines:

```Dockerfile
RUN mkdir /data
# ...
ENV DATABASE_URL="sqlite3:///data/production.sqlite3" 
# ...
VOLUME /data
```

A few notes:

- The scanner.rb correctly does not set `@sqlite3 = true`
- However `dockerfile_generator.rb` [sets a default to sqlite3](https://github.com/fly-apps/dockerfile-rails/blob/ae575f92ad7c93c5df1f23c7c759b66da36dfeff/lib/generators/dockerfile_generator.rb#L912)
- The Readme seems to imply that if this tool cannot infer the database correctly, you will need to specify it, such as specifying `--sqlite3` from the [Add a Database](https://github.com/fly-apps/dockerfile-rails/tree/ae575f92ad7c93c5df1f23c7c759b66da36dfeff#add-a-database) section.

I can appreciate that adding sqlite3 as a default is probably convenient or likely, however, if it _is_ being used, it will be in the gemfile, or the database config, and as such, will be detected and should not be assumed unless specified. Because it is, I am manually editing the Dockerfile, even though it's otherwise entirely autogenerated from my `config/dockerfile.yml` config file.

Would you consider removing the default value for `#deploy_database`, and require checking as you do for pg and mysql?

**Comment by rubys** [comment]
Would supporting sqlserver address your needs?

https://github.com/fly-apps/dockerfile-rails/commit/40a1f9ba39682f1c6763fff9983acd03fbfcff30

**Comment by ttilberg** [comment]
That would be even better! Cheers!
