### ISSUE TITLE
Node being installed even if Bun is being used

### ISSUE THREAD

**Issue by luizkowalski** [fly-apps/dockerfile-rails#70]
hey 👋🏻 

I see this issue where node is installed in the image and `.node-version` is generated even if Bun is being used. This can cause problems, as [I found before](https://github.com/oven-sh/bun/issues/5561#issuecomment-1836977798). 

I think that `using_node?` method just checks for `package.json` existence which is not 100% correct since Bun also uses this. I believe that `using_node?` should also check I'm not `using_bun?`

**Comment by rubys** [comment]
Care to make a pull request?  Unless it breaks an existing test, I'll merge it.

**Comment by luizkowalski** [comment]
Sure, opened up one in draft, and will pick it up tomorrow, almost the next day here on the other side of the ocean hahaha
