### ISSUE TITLE
Latest Rubygems no longer supports Ruby < 3

### ISSUE THREAD

**Issue by Antsiscool** [fly-apps/dockerfile-rails#83]
The following is failing when building with Ruby 2.7.8.

```
RUN gem update --system --no-document && \
    gem install -N bundler
```

Rubygems has dropped support for Ruby 2.6 and 2.7 in version 3.5.0.
https://github.com/rubygems/rubygems/releases/tag/v3.5.0

This can be fixed by specifying the latest version of rubygems that is compatible with these version of Ruby. e.g.

```
RUN gem update --system 3.4.22 --no-document && \
    gem install -N bundler
```

**Comment by rubys** [comment]
Thanks!  Released.
